services:
  # Automation service (file watcher + queue worker)
  automation:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: polar-automation
    volumes:
      - ./docker/backend/data/queues:/app/queues:rw
      - ./docker/backend/data/state:/app/state:rw
      - ./docker/backend/data/sessions:/app/sessions:ro
      - ./frontend/public/data:/app/output:rw
      #      - ./docker/frontend/data/charts:/app/output:rw TODO: configure nginx to be able to serve from different
      #      directories
    profiles:
      - automation
    restart: unless-stopped

  # Manual processor service (for one-off runs)
  processor:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: polar-processor
    volumes:
      - ./sessions:/app/sessions:ro
      - ./frontend/public/data:/app/output:rw
    profiles:
      - process
    entrypoint: ["python", "src/session_processor.py"]
    command: ["--help"]

  web:
    image: nginx:alpine
    container_name: polar-web-server
    ports:
      - "13000:80"
    volumes:
#      - ./docker/frontend/data/charts:/app/charts:ro TODO: configure nginx to be able to serve from different directories
      - ./frontend/public:/usr/share/nginx/html:ro
    profiles:
      - web
